name: Build
on:
  push:
    branches: ["**"]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build and Push
        uses: orthofi/actions-build-and-push-nuget@v1
        with:
          github-token: ${{ secrets.BUILD_GITHUB_TOKEN }}
