name: Build
on:
  push:
    branches: ["**"]
jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.BUILD_GITHUB_TOKEN }}
      GITHUB_USERNAME: OrthoFi
      APP_NAME: template-api

    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Tools
        run: dotnet tool install -g Amazon.ElasticBeanstalk.Tools

      - name: Build
        run: dotnet build --nologo -c Release

      - name: Test
        run: dotnet test --no-build -c Release --nologo -r out_tests --collect:"XPlat Code Coverage"

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: tests
          path: out_tests

      - name: Package Beanstalk
        run: dotnet eb package -pl ./Api -o ./artifacts/beanstalk.zip

      - name: Upload Beanstalk Zip
        uses: actions/upload-artifact@v2
        with:
          name: beanstalk
          path: ./artifacts/beanstalk.zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.OCKERS_BUILD_ROLE }}

      - name: Api Image
        uses: orthofi/actions-build-docker@v1
        with:
          context: .
          dockerfile: ./Api/Dockerfile
          image-name: ${{ env.APP_NAME }}
          github-token: ${{ secrets.BUILD_GITHUB_TOKEN }}
