name: Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Target Environment
        required: true
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: orthofi/actions-verify-environment@v1
        with:
          environment: ${{ github.event.inputs.environment }}
          token: ${{ secrets.BUILD_GITHUB_TOKEN }}

  beanstalk:
    runs-on: ubuntu-latest
    needs: [init]
    environment: ${{ github.event.inputs.environment }}-beanstalk
    steps:
      - name: Deploy Beanstalk
        uses: orthofi/actions-deploy-beanstalk@v1
        with:
          app-name: template
          app-env-name: ${{ github.event.inputs.environment }}
          aws-dev-build-role: ${{ secrets.OCKERS_BUILD_ROLE }}
          aws-production-build-role: ${{ secrets.PRODUCTION_BUILD_ROLE }}
          aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
          sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}

  lambda:
    runs-on: ubuntu-latest
    needs: [init]
    environment: ${{ github.event.inputs.environment }}-lambda
    steps:
      - name: Deploy Lambda
        uses: orthofi/actions-deploy-lambda@v2
        with:
          app-name: template
          app-env-name: ${{ github.event.inputs.environment }}
          aws-dev-build-role: ${{ secrets.OCKERS_BUILD_ROLE }}
          aws-production-build-role: ${{ secrets.PRODUCTION_BUILD_ROLE }}
          aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
          sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
