name: Publish NuGet
on:
  push:
    branches: [main, develop]
  workflow_dispatch:
jobs:
  build-and-publush:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Add NuGet Source
        run: dotnet nuget add source https://nuget.pkg.github.com/OrthoFi/index.json -n GitHub -u OrthoFi -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

      - name: Configure GitHub User
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Generate Version
        run: |
          npm i standard-version

          if [ "${GITHUB_REF#refs/heads/}" == "main" ];
          then
            npx standard-version
          else
            npx standard-version -p "${GITHUB_REF#refs/heads/}+${GITHUB_RUN_NUMBER}"
          fi

      - name: Build
        run: dotnet build --nologo -c Release

      - name: Test
        run: dotnet test --no-build -c Release --nologo -r out_tests --logger "trx" --collect "Code Coverage"

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: tests
          path: out_tests

      - name: Package
        run: dotnet pack -o out --no-build -c Release

      - name: Upload
        run: dotnet nuget push "out/*.nupkg" -s GitHub -k ${{ secrets.GITHUB_TOKEN }}

      - name: Push
        if: github.ref == 'refs/heads/main'
        run: git push --follow-tags
