name: Trigger Automated Deploy
on:
  workflow_run:
    workflows:
      - Build
    branches: [main, risk, dev]
    types:
      - completed

jobs:
  init:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      TARGET_BRANCH: ${{ github.event.workflow_run.head_branch }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Initiate Deploy Workflow
        uses: orthofi/actions-initiate-automated-deploy@v1
        with:
          branch: ${{ env.TARGET_BRANCH }}
          token: ${{ secrets.BUILD_GITHUB_TOKEN }}
